### ISSUE TITLE
Hello,thank you for your code.

### ISSUE THREAD

**Issue by CharmingYoona** [simo23/tinyYOLOv2#7]
My question is ,is the network in net.py is based on MobilenetV1? I want to change the net.py based on MobilenetV2,what should I do ? Thank you very much!

**Comment by simo23** [comment]
Hi @CharmingYoona,

no the network is called Darknet and it is not Mobilenet. The architecture has been created by the authors of YOLO. You can have more details in their papers, like [YOLOv2](https://arxiv.org/pdf/1612.08242.pdf). 

If you want to use Mobilenet it this project to detect things you will not be able to do it. The reason is that you need a **trained** model, and it is not available. You can define net.py as Mobilenet if you want, but then you must find a way to train it otherwise the results will be awful. Maybe someone else has done something like this. I know of other repositories of other object detectors like SSD which have Mobilenet as the feature extractor. You can try to see if one of those projects works for you!

**Comment by CharmingYoona** [comment]
@simo23 Thank you,thank you very much.
