### ISSUE TITLE
Support YOLOv2

### ISSUE THREAD

**Issue by LucasMahieu** [simo23/tinyYOLOv2#9]
Did you plan to support YOLOv2 ?
If yes, do you know when ?
If no, do you know why ?
And what we could do to help to do it ?

Thanks

**Comment by simo23** [comment]
Hi,

no I did not plan to support YOLOv2 sorry. The reason is that I wanted the lightest network to perform detection, so I went for the tiny one. If you want to use YOLOv2 (or any other) it should be quite straightforward. You should:

- download the cfg file and take a look at the architecture which is defined in there
- change the architecture of the network in net.py (very few changes)
- change the weights_loader.load() fn in the same way
- download the new weights

Done!
